In [5]:
import pandas as pd
values=[10,20,30,40,50]
y=pd.Series(values)
x=pd.Series(values,index=['a','a','c','d','a'])
print(x)
print(y)

a    10
a    20
c    30
d    40
a    50
dtype: int64
0    10
1    20
2    30
3    40
4    50
dtype: int64

In [25]:
def space():
    print("-"*20)

In [ ]:
# duplicate
x.loc['a']#by using the index we can easily access the value in the x

a    10
a    20
a    50
dtype: int64

In [17]:
# dataframe
df=pd.DataFrame({
    'name':['milke','ti','sam'],
    'age':[12,14,54],
    'comapany':['ama','flip','colab']
})
df

    name  age comapany
0  milke   12      ama
1     ti   14     flip
2    sam   54    colab

In [26]:
dg=df.set_index('name')
print(dg)
space()
print(df.columns)

       age comapany
name
milke   12      ama
ti      14     flip
sam     54    colab
--------------------
Index(['name', 'age', 'comapany'], dtype='object')

In [28]:
df1=pd.DataFrame({
    'a':[1,2,3]
})
df2=pd.DataFrame({
    'a':[10,20,30]
})
df1+df2

    a
0  11
1  22
2  33

In [ ]:
df1=pd.DataFrame({
    'a':[1,2,3]
},index=[0,1,2])
df2=pd.DataFrame({
    'a':[10,20,30]
},index=[1,2,0])
df1+df2#the same index only get add togeather

    a
0  31
1  12
2  23

In [35]:
df1=pd.DataFrame({
    'a':[1,2,3]
})
df2=pd.DataFrame({
    'a':[10,20,30,40]
})
df1+df2

      a
0  11.0
1  22.0
2  33.0
3   NaN

In [37]:
df1=pd.DataFrame({
    'a':[1,2,3]
},index=[1,2,3])
df2=pd.DataFrame({
    'a':[10,20,30,40]
},index=[1,2,3,4])
df1+df2

      a
1  11.0
2  22.0
3  33.0
4   NaN

In [38]:
df1=pd.DataFrame({
    'a':[1,2,3]
},index=[1,2,3])
df2=pd.DataFrame({
    'a':[10,20,30]
},index=[4,5,6])
df1+df2

    a
1 NaN
2 NaN
3 NaN
4 NaN
5 NaN
6 NaN

In [39]:
df

    name  age comapany
0  milke   12      ama
1     ti   14     flip
2    sam   54    colab

In [40]:
df=df.reset_index()

In [41]:
df

   index   name  age comapany
0      0  milke   12      ama
1      1     ti   14     flip
2      2    sam   54    colab

In [ ]:
df.to_csv('mydata.csv')#just type df.to_ -->and from here you can choose the format you want

In [43]:
b=pd.read_csv("mydata.csv")
b

   Unnamed: 0  index   name  age comapany
0           0      0  milke   12      ama
1           1      1     ti   14     flip
2           2      2    sam   54    colab

In [44]:
c=pd.read_csv("mydata.csv",index_col=0)#this index_column tells that the first column of the file is indeed the first column
c

   index   name  age comapany
0      0  milke   12      ama
1      1     ti   14     flip
2      2    sam   54    colab

In [45]:
# to export your data without the index to any file foramte
# for ex take csv
df.to_csv("hey_csv.csv",index=None)

In [47]:
df.to_json("file.json")

In [49]:
df.to_dict()

{'index': {0: 0, 1: 1, 2: 2},
 'name': {0: 'milke', 1: 'ti', 2: 'sam'},
 'age': {0: 12, 1: 14, 2: 54},
 'comapany': {0: 'ama', 1: 'flip', 2: 'colab'}}